---
- hosts: Switch
  gather_facts: false
  connection: network_cli
  vars:
    cli:
      host: "{{ inventory_hostname }}"
      ansible_user: "{{ username }}"
      ansible_ssh_pass: "{{ password }}"
      ansible_become: yes
      ansible_become_method: enable
      ansible_become_pass: "{{ password }}"

  tasks:
  - name: get file from devices
    net_get:
      src: master.cfg
