---
- hosts: Switch
  gather_facts: false
  #connection: local
  vars:
    cli:
      host: "{{ inventory_hostname }}"
      username: "{{ username }}"
      password: "{{ password }}"
      authorize: yes
      auth_pass: "{{ password }}"

  tasks:
  - name: verify arp and interface on devices
    ios_command:
      commands: 
        - show arp | inc Internet
        - show interface GigabitEthernet0/1
        - show interface GigabitEthernet0/7
        - show interface GigabitEthernet0/8
        - show spanning-tree summary
        - show cdp neig | beg Device ID
      provider: "{{ cli }}"
      wait_for: 
        - result[0] contains 192.168.98.1
        - result[1] contains '0 input errors, 0 CRC, 0 frame, 0 overrun, 0 ignored'
        - result[2] contains '0 input errors, 0 CRC, 0 frame, 0 overrun, 0 ignored'
        - result[3] contains '0 input errors, 0 CRC, 0 frame, 0 overrun, 0 ignored'
        - result[4] contains 'VLAN0001, VLAN0006-VLAN0015'
        - result[5] contains AP1602i
        - result[5] contains esx1 
    delegate_to: localhost
    ignore_errors: yes
    register: switch

  - name: switch fail
    debug: 
      msg: "Expected x+y , '{{ switch.failed_conditions }}'"
    when: switch is failed

  - name: Send notification message via Slack all options
    slack:
      token: '{{ slack_token }}'
      msg: Switch '{{ inventory_hostname }} failed'
      channel: #ansible_awx
      username: 'Ansible on {{ inventory_hostname }}'
      icon_url: http://docs.ansible.com/ansible/latest/_static/images/logo_invert.png
      link_names: 0
      parse: 'none'
    delegate_to: localhost
    when: switch is failed

- hosts: AP
  gather_facts: false
  #connection: local
  vars:
    cli:
      host: "{{ inventory_hostname }}"
      username: christer
      password: hemgren
      authorize: yes
      auth_pass: hemgren

  tasks:
  - name: verify wifi, ntp and interface on devices
    ios_command:
      commands: 
        - show dot11 ass
        - show dot11 bssid
        - show sntp
        - show interface summary
        #- show spanning-tree summary
      provider: "{{ cli }}"
      wait_for: 
        - result[0] contains 192.168.96.
        - result[1] contains Dot11Radio0
        - result[1] contains Dot11Radio1
        - result[2] contains Synced
        - result[3] contains BVI1
    delegate_to: localhost
    ignore_errors: yes
    register: wifi

  - name: AP fail
    debug: 
      msg: "Expected x+y , '{{ wifi.failed_conditions }}'"
    when: wifi|failed

  - name: Send notification message via Slack
    slack:
      token: '{{ slack_token }}'
      msg: AP '{{ inventory_hostname }} failed'
      username: 'Ansible on {{ inventory_hostname }}'
      channel: #ansible_awx      
      icon_url: http://docs.ansible.com/ansible/latest/_static/images/logo_invert.png
      link_names: 0
      parse: 'none'
    delegate_to: localhost
    when: wifi is failed

- hosts: ASA
  gather_facts: false
  vars:
    cli:
      host: "{{ inventory_hostname }}"
      username: "{{ username }}"
      password: "{{ password }}"
      authorize: yes
      auth_pass: "{{ password }}"
      #transport: cli

  tasks:
  - name: verify inv, route, arp and ntp
    asa_command:
      commands: 
      - show inventory
      - show route connec
      - show arp
      #- show dhcpd bind
      - show ntp status
      provider: "{{ cli }}"
      wait_for: 
        - result[0] contains ASA5505
        - result[1] contains 'network 0.0.0.0'
        - result[2] contains outside
        - result[2] contains wlan96
        - result[3] contains 'Clock is synchronized'
    register: asa
    ignore_errors: yes
    delegate_to: localhost

#  - name: asa command
#    debug: var=asa.failed_conditions
  - name: asa fail
    debug: 
      msg: "Expected ASA5505 , '{{ asa.failed_conditions }}'"
    when: asa is failed

  - name: Send notification message via Slack all options
    slack:
      token: '{{ slack_token }}'
      msg: Firewall '{{ inventory_hostname }} failed'
      channel: #ansible_awx
      #username: 'Ansible on {{ inventory_hostname }}'
      color: warning
      icon_url: http://docs.ansible.com/ansible/latest/_static/images/logo_invert.png
      link_names: 0
      parse: 'none'
    delegate_to: localhost
    when: asa is failed
