---
- hosts: "{{ hosts_vars }}"
  gather_facts: false
  connection: local
  vars:
    provider:
      host: "{{ inventory_hostname }}"
      username: "{{ username }}"
      password: "{{ password }}"
      #ansible_network_os: "{{ network_os }}"

  tasks:
  - name: Test reachability to 10.10.10.10 using default vrf
    ios_ping:
      provider: "{{ provider }}"
      #dest: 192.168.98.1
      dest: "{{ ping_to }}"

  - name: Test reachability to 10.10.10.10 using default vrf
    net_ping:
      provider: "{{ provider }}"
      #dest: 192.168.98.1
      dest: "{{ ping_to }}"

#- name: Test reachability to 10.20.20.20 using prod vrf
#  net_ping:
#    provider: "{{ provider }}"
#    dest: 10.20.20.20
#    vrf: prod

#- name: Test unreachability to 10.30.30.30 using default vrf
#  net_ping:
#    provider: "{{ provider }}"
#    dest: 10.30.30.30
#    state: absent

#  - name: Test reachability to 10.40.40.40 using prod vrf and setting count and source
#    net_ping:
#      provider: "{{ provider }}"
#      dest: 10.40.40.40
#      source: loopback0
#      vrf: prod
#      count: 20
