- hosts: localhost
  gather_facts: false
  connection: local
  tasks:
# Gather IP facts from ipify.org
  - name: get my public IP
    ipify_facts:
    when: my_ip2 is defined

  - name: My public IP 
    #debug: msg= "{{ ipify_public_ip }}"
    debug: var=ipify_public_ip
    when: my_ip2 is defined

# Gather IP facts from your own ipify service endpoint
#- name: get my public IP
#  ipify_facts: api_url=http://api.example.com/ipify

  - name: "Save public IP results to Tower Workflows"
    set_stats:
      data:
        my_public_ip:  "{{ ipify_public_ip }}"
    when: my_ip2 is defined
