- hosts: localhost
  gather_facts: false
  connection: local
  tasks:
# Gather IP facts from ipify.org
  - name: get my public IP
    ipify_facts:
    when: my_ip1 is defined
    #when: my_ip == "my_ip1"

  - name: My public IP 
    #debug: msg= "{{ ipify_public_ip }}"
    debug: var=ipify_public_ip
    when: my_ip1 is defined
    #when: my_ip == "my_ip1"

  # Retrieve geolocation data of a host's IP address
  - name: get IP geolocation data
    ipinfoio_facts:

  - name: My GeoIP > Country, Region and City
    debug:
      msg: "{{ ansible_facts.country }}, {{ ansible_facts.region }}, {{ ansible_facts.city }}"

# Gather IP facts from your own ipify service endpoint
#- name: get my public IP
#  ipify_facts: api_url=http://api.example.com/ipify
